### ISSUE TITLE
Error when installing gdal dependency

### ISSUE THREAD

**Issue by ghing** [ghing/tiger-boundaries#2]
A bit of the error log, though I can't make much sense of it:

```
...
In file included from ../../nan/nan.h:2657,
                 from ../src/utils/fast_buffer.hpp:11,
                 from ../src/utils/fast_buffer.cpp:4:
../../nan/nan_object_wrap.h: In member function ‘void Nan::ObjectWrap::MakeWeak()’:
../../nan/nan_object_wrap.h:67:18: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘MarkIndependent’
   67 |     persistent().MarkIndependent();
      |                  ^~~~~~~~~~~~~~~
../src/utils/fast_buffer.cpp: In static member function ‘static v8::Local<v8::Value> FastBuffer::New(unsigned char*, int)’:
../src/utils/fast_buffer.cpp:15:88: error: no matching function for call to ‘v8::Object::Get(v8::Local<v8::String>)’
   15 |  Local<Function> bufferConstructor = globalObj->Get(Nan::New("Buffer").ToLocalChecked()).As<Function>();
      |                                                                                        ^
In file included from /home/codespace/.cache/node-gyp/14.15.1/include/node/node.h:67,
                 from ../src/utils/fast_buffer.hpp:5,
                 from ../src/utils/fast_buffer.cpp:4:
/home/codespace/.cache/node-gyp/14.15.1/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
 3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/codespace/.cache/node-gyp/14.15.1/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/home/codespace/.cache/node-gyp/14.15.1/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
 3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/codespace/.cache/node-gyp/14.15.1/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
../src/utils/fast_buffer.cpp:15:101: error: expected primary-expression before ‘>’ token
   15 |  Local<Function> bufferConstructor = globalObj->Get(Nan::New("Buffer").ToLocalChecked()).As<Function>();
      |                                                                                                     ^
../src/utils/fast_buffer.cpp:15:103: error: expected primary-expression before ‘)’ token
   15 |  Local<Function> bufferConstructor = globalObj->Get(Nan::New("Buffer").ToLocalChecked()).As<Function>();
      |                                                                                                       ^
make: *** [gdal.target.mk:171: Release/obj.target/gdal/src/utils/fast_buffer.o] Error 1
make: Leaving directory '/workspaces/appalachia/node_modules/gdal/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/14.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-1040-azure
gyp ERR! command "/opt/nodejs/14.15.1/bin/node" "/opt/nodejs/14.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/workspaces/appalachia/node_modules/gdal/lib/binding/node-v83-linux-x64/gdal.node" "--module_name=gdal" "--module_path=/workspaces/appalachia/node_modules/gdal/lib/binding/node-v83-linux-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /workspaces/appalachia/node_modules/gdal
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/nodejs/14.15.1/bin/node /opt/nodejs/14.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/workspaces/appalachia/node_modules/gdal/lib/binding/node-v83-linux-x64/gdal.node --module_name=gdal --module_path=/workspaces/appalachia/node_modules/gdal/lib/binding/node-v83-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/workspaces/appalachia/node_modules/gdal/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.4.0-1040-azure
node-pre-gyp ERR! command "/opt/nodejs/14.15.1/bin/node" "/workspaces/appalachia/node_modules/gdal/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /workspaces/appalachia/node_modules/gdal
node-pre-gyp ERR! node -v v14.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/opt/nodejs/14.15.1/bin/node /opt/nodejs/14.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/workspaces/appalachia/node_modules/gdal/lib/binding/node-v83-linux-x64/gdal.node --module_name=gdal --module_path=/workspaces/appalachia/node_modules/gdal/lib/binding/node-v83-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gdal@0.9.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gdal@0.9.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/codespace/.npm/_logs/2021-03-17T17_19_11_990Z-debug.log
```

**Comment by ghing** [comment]
This was addressed by c953860. Closing.
